name = "secure-chat"
main = "dist/SecureChat.js"
compatibility_date = "2024-01-01"

# D1 Database binding
[[d1_databases]]
binding = "DB"
database_name = "secure-chat-db"
database_id = "your-database-id"

# KV Namespace binding for sessions
[[kv_namespaces]]
binding = "KV"
id = "your-kv-namespace-id"
preview_id = "your-preview-kv-namespace-id"

# Environment variables
[vars]
ENVIRONMENT = "development"
API_VERSION = "1.0.0"

# Secrets - Set these using wrangler commands:
# wrangler secret put USER_ALICE_PASSWORD
# wrangler secret put USER_BOB_PASSWORD
# Add more users as needed following the pattern: USER_<USERNAME>_PASSWORD